// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DATABASE_OBSERVER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DATABASE_OBSERVER_METHOD0
typedef void (*UniffiCallbackInterfaceDatabaseObserverMethod0)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DATABASE_OBSERVER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DATABASE_OBSERVER
typedef struct UniffiVTableCallbackInterfaceDatabaseObserver {
    UniffiCallbackInterfaceDatabaseObserverMethod0 _Nonnull onDatabaseChanged;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceDatabaseObserver;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_INIT_CALLBACK_VTABLE_DATABASEOBSERVER
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_INIT_CALLBACK_VTABLE_DATABASEOBSERVER
void uniffi_yntra_core_fn_init_callback_vtable_databaseobserver(UniffiVTableCallbackInterfaceDatabaseObserver* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ACTIVATE_INVITATION_CODE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ACTIVATE_INVITATION_CODE
RustBuffer uniffi_yntra_core_fn_func_activate_invitation_code(RustBuffer code, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_CLIENT_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_CLIENT_VIA_DIRECTORY
RustBuffer uniffi_yntra_core_fn_func_add_client_via_directory(RustBuffer workspace_id, RustBuffer team_id, RustBuffer first_name, RustBuffer last_name, RustBuffer personal_number, RustBuffer care_level, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_EVENT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_EVENT
RustBuffer uniffi_yntra_core_fn_func_add_event(RustBuffer title, RustBuffer start_time, RustBuffer end_time, RustBuffer team_id, RustBuffer assignee_id, RustBuffer recipient_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_EVENT_WITH_METADATA
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_EVENT_WITH_METADATA
RustBuffer uniffi_yntra_core_fn_func_add_event_with_metadata(RustBuffer title, RustBuffer start_time, RustBuffer end_time, RustBuffer team_id, RustBuffer assignee_id, RustBuffer recipient_id, RustBuffer metadata, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_JOURNAL_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_JOURNAL_ENTRY
RustBuffer uniffi_yntra_core_fn_func_add_journal_entry(RustBuffer client_id, RustBuffer author_id, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_MEDICATION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_MEDICATION
RustBuffer uniffi_yntra_core_fn_func_add_medication(RustBuffer client_id, RustBuffer name, RustBuffer dosage, RustBuffer frequency, RustBuffer instructions, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_NOTE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_NOTE
RustBuffer uniffi_yntra_core_fn_func_add_note(RustBuffer team_id, RustBuffer author_id, RustBuffer subject, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_REPORT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_REPORT
RustBuffer uniffi_yntra_core_fn_func_add_report(RustBuffer user_id, RustBuffer report_type, int8_t is_anonymous, RustBuffer subject, RustBuffer description, RustBuffer date_of_incident, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_TEAM_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_TEAM_VIA_DIRECTORY
RustBuffer uniffi_yntra_core_fn_func_add_team_via_directory(RustBuffer workspace_id, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_TIME_REPORT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_TIME_REPORT
RustBuffer uniffi_yntra_core_fn_func_add_time_report(RustBuffer user_id, RustBuffer team_id, RustBuffer date, double hours, RustBuffer note, RustBuffer start_time, RustBuffer end_time, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_TODO
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_ADD_TODO
RustBuffer uniffi_yntra_core_fn_func_add_todo(RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_AUTHENTICATE_WITH_NFC
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_AUTHENTICATE_WITH_NFC
RustBuffer uniffi_yntra_core_fn_func_authenticate_with_nfc(RustBuffer badge_uid, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_AUTHENTICATE_WITH_SITHS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_AUTHENTICATE_WITH_SITHS
RustBuffer uniffi_yntra_core_fn_func_authenticate_with_siths(RustBuffer card_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_CLEAR_OBSERVERS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_CLEAR_OBSERVERS
void uniffi_yntra_core_fn_func_clear_observers(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_COMPLETE_AUTH_SESSION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_COMPLETE_AUTH_SESSION
void uniffi_yntra_core_fn_func_complete_auth_session(RustBuffer session_id, RustBuffer user_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_CREATE_JOB_TICKET
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_CREATE_JOB_TICKET
RustBuffer uniffi_yntra_core_fn_func_create_job_ticket(RustBuffer workspace_id, RustBuffer title, RustBuffer description, RustBuffer location_address, RustBuffer priority, RustBuffer assigned_user_id, RustBuffer scheduled_date, RustBuffer checklist_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_CREATE_WORKSPACE_VIA_HUB
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_CREATE_WORKSPACE_VIA_HUB
void uniffi_yntra_core_fn_func_create_workspace_via_hub(RustBuffer name, RustBuffer admin_email, RustBuffer modules_active, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_EVENT
void uniffi_yntra_core_fn_func_delete_event(RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_NOTE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_NOTE
void uniffi_yntra_core_fn_func_delete_note(RustBuffer note_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_TIME_REPORT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_TIME_REPORT
void uniffi_yntra_core_fn_func_delete_time_report(RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_WORKSPACE_VIA_HUB
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_DELETE_WORKSPACE_VIA_HUB
void uniffi_yntra_core_fn_func_delete_workspace_via_hub(RustBuffer workspace_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_FAIL_AUTH_SESSION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_FAIL_AUTH_SESSION
void uniffi_yntra_core_fn_func_fail_auth_session(RustBuffer session_id, RustBuffer error_msg, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GENERATE_TOTP_SECRET
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GENERATE_TOTP_SECRET
RustBuffer uniffi_yntra_core_fn_func_generate_totp_secret(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_BANKID_AUTH_SESSION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_BANKID_AUTH_SESSION
RustBuffer uniffi_yntra_core_fn_func_get_bankid_auth_session(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_BLOCKS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_BLOCKS
RustBuffer uniffi_yntra_core_fn_func_get_blocks(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_CLIENTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_CLIENTS
RustBuffer uniffi_yntra_core_fn_func_get_clients(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_EVENTS
RustBuffer uniffi_yntra_core_fn_func_get_events(RustBuffer team_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_JOB_TICKETS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_JOB_TICKETS
RustBuffer uniffi_yntra_core_fn_func_get_job_tickets(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_JOURNALS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_JOURNALS
RustBuffer uniffi_yntra_core_fn_func_get_journals(RustBuffer client_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_MEDICATIONS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_MEDICATIONS
RustBuffer uniffi_yntra_core_fn_func_get_medications(RustBuffer client_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_MESSAGES
RustBuffer uniffi_yntra_core_fn_func_get_messages(RustBuffer user_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_NOTES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_NOTES
RustBuffer uniffi_yntra_core_fn_func_get_notes(RustBuffer team_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_REPORTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_REPORTS
RustBuffer uniffi_yntra_core_fn_func_get_reports(int8_t is_admin, RustBuffer user_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_TEAMS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_TEAMS
RustBuffer uniffi_yntra_core_fn_func_get_teams(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_TIME_REPORTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_TIME_REPORTS
RustBuffer uniffi_yntra_core_fn_func_get_time_reports(RustBuffer user_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_TODOS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_TODOS
RustBuffer uniffi_yntra_core_fn_func_get_todos(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_USERS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_USERS
RustBuffer uniffi_yntra_core_fn_func_get_users(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_WORKSPACE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_WORKSPACE
RustBuffer uniffi_yntra_core_fn_func_get_workspace(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_WORKSPACES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_GET_WORKSPACES
RustBuffer uniffi_yntra_core_fn_func_get_workspaces(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_INITIATE_BANKID_AUTH
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_INITIATE_BANKID_AUTH
RustBuffer uniffi_yntra_core_fn_func_initiate_bankid_auth(RustBuffer target_role, RustBuffer provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_INVITE_USER_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_INVITE_USER_VIA_DIRECTORY
RustBuffer uniffi_yntra_core_fn_func_invite_user_via_directory(RustBuffer workspace_id, RustBuffer email, RustBuffer name, RustBuffer role, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_MARK_MESSAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_MARK_MESSAGE_READ
void uniffi_yntra_core_fn_func_mark_message_read(RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_REGISTER_OBSERVER
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_REGISTER_OBSERVER
void uniffi_yntra_core_fn_func_register_observer(uint64_t observer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SEND_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SEND_MESSAGE
RustBuffer uniffi_yntra_core_fn_func_send_message(RustBuffer sender_id, RustBuffer receiver_id, RustBuffer team_id, RustBuffer subject, RustBuffer body, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SET_USER_PASSWORD
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SET_USER_PASSWORD
void uniffi_yntra_core_fn_func_set_user_password(RustBuffer user_id, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SUBMIT_BANKID_PIN
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SUBMIT_BANKID_PIN
void uniffi_yntra_core_fn_func_submit_bankid_pin(RustBuffer session_id, RustBuffer pin, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SUBMIT_JOB_COMPLETION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SUBMIT_JOB_COMPLETION
void uniffi_yntra_core_fn_func_submit_job_completion(RustBuffer job_id, RustBuffer checklist_json, RustBuffer completion_report, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SYNC_DATABASE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_SYNC_DATABASE
void uniffi_yntra_core_fn_func_sync_database(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_TOGGLE_TODO
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_TOGGLE_TODO
void uniffi_yntra_core_fn_func_toggle_todo(RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_AUTH_SESSION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_AUTH_SESSION_STATUS
void uniffi_yntra_core_fn_func_update_auth_session_status(RustBuffer session_id, RustBuffer status, double progress, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_CLIENT_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_CLIENT_PROFILE
void uniffi_yntra_core_fn_func_update_client_profile(RustBuffer client_id, RustBuffer first_name, RustBuffer last_name, RustBuffer personal_number, RustBuffer care_level, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_EVENT
void uniffi_yntra_core_fn_func_update_event(RustBuffer id, RustBuffer title, RustBuffer start_time, RustBuffer end_time, RustBuffer team_id, RustBuffer assignee_id, RustBuffer recipient_id, RustBuffer metadata, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_EVENT_TIME
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_EVENT_TIME
void uniffi_yntra_core_fn_func_update_event_time(RustBuffer id, RustBuffer start_time, RustBuffer end_time, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_JOB_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_JOB_STATUS
void uniffi_yntra_core_fn_func_update_job_status(RustBuffer job_id, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_NOTE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_NOTE
RustBuffer uniffi_yntra_core_fn_func_update_note(RustBuffer note_id, RustBuffer edited_by_name, RustBuffer subject, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_REPORT_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_REPORT_STATUS
void uniffi_yntra_core_fn_func_update_report_status(RustBuffer report_id, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_TIME_REPORT_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_TIME_REPORT_STATUS
void uniffi_yntra_core_fn_func_update_time_report_status(RustBuffer id, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_USER_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_USER_PROFILE
void uniffi_yntra_core_fn_func_update_user_profile(RustBuffer user_id, RustBuffer full_name, RustBuffer phone, RustBuffer preferences, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_USER_ROLE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_USER_ROLE
void uniffi_yntra_core_fn_func_update_user_role(RustBuffer user_id, RustBuffer role, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_USER_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_USER_VIA_DIRECTORY
void uniffi_yntra_core_fn_func_update_user_via_directory(RustBuffer user_id, RustBuffer full_name, RustBuffer phone, RustBuffer role, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_WORKSPACE_GENERAL
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_WORKSPACE_GENERAL
void uniffi_yntra_core_fn_func_update_workspace_general(RustBuffer name, RustBuffer brand_color, RustBuffer logo_url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_WORKSPACE_MODULES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_WORKSPACE_MODULES
void uniffi_yntra_core_fn_func_update_workspace_modules(RustBuffer modules_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_WORKSPACE_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_UPDATE_WORKSPACE_SETTINGS
void uniffi_yntra_core_fn_func_update_workspace_settings(RustBuffer settings_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_VERIFY_EMAIL_PASSWORD
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_VERIFY_EMAIL_PASSWORD
RustBuffer uniffi_yntra_core_fn_func_verify_email_password(RustBuffer email, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_VERIFY_USER_TOTP
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_FN_FUNC_VERIFY_USER_TOTP
int8_t uniffi_yntra_core_fn_func_verify_user_totp(RustBuffer secret, RustBuffer code, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_yntra_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_yntra_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_FREE
void ffi_yntra_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_yntra_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U8
void ffi_yntra_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U8
void ffi_yntra_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U8
void ffi_yntra_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_yntra_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I8
void ffi_yntra_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I8
void ffi_yntra_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I8
void ffi_yntra_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_yntra_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U16
void ffi_yntra_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U16
void ffi_yntra_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U16
void ffi_yntra_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_yntra_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I16
void ffi_yntra_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I16
void ffi_yntra_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I16
void ffi_yntra_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_yntra_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U32
void ffi_yntra_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U32
void ffi_yntra_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U32
void ffi_yntra_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_yntra_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I32
void ffi_yntra_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I32
void ffi_yntra_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I32
void ffi_yntra_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_yntra_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_U64
void ffi_yntra_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_U64
void ffi_yntra_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_U64
void ffi_yntra_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_yntra_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_I64
void ffi_yntra_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_I64
void ffi_yntra_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_I64
void ffi_yntra_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_yntra_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_F32
void ffi_yntra_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_F32
void ffi_yntra_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_F32
void ffi_yntra_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_yntra_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_F64
void ffi_yntra_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_F64
void ffi_yntra_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_F64
void ffi_yntra_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_yntra_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_POINTER
void ffi_yntra_core_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_POINTER
void ffi_yntra_core_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_POINTER
void ffi_yntra_core_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_yntra_core_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_yntra_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_yntra_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_yntra_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_yntra_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_POLL_VOID
void ffi_yntra_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_yntra_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_FREE_VOID
void ffi_yntra_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_yntra_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ACTIVATE_INVITATION_CODE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ACTIVATE_INVITATION_CODE
uint16_t uniffi_yntra_core_checksum_func_activate_invitation_code(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_CLIENT_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_CLIENT_VIA_DIRECTORY
uint16_t uniffi_yntra_core_checksum_func_add_client_via_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_EVENT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_EVENT
uint16_t uniffi_yntra_core_checksum_func_add_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_EVENT_WITH_METADATA
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_EVENT_WITH_METADATA
uint16_t uniffi_yntra_core_checksum_func_add_event_with_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_JOURNAL_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_JOURNAL_ENTRY
uint16_t uniffi_yntra_core_checksum_func_add_journal_entry(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_MEDICATION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_MEDICATION
uint16_t uniffi_yntra_core_checksum_func_add_medication(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_NOTE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_NOTE
uint16_t uniffi_yntra_core_checksum_func_add_note(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_REPORT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_REPORT
uint16_t uniffi_yntra_core_checksum_func_add_report(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_TEAM_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_TEAM_VIA_DIRECTORY
uint16_t uniffi_yntra_core_checksum_func_add_team_via_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_TIME_REPORT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_TIME_REPORT
uint16_t uniffi_yntra_core_checksum_func_add_time_report(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_TODO
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_ADD_TODO
uint16_t uniffi_yntra_core_checksum_func_add_todo(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_AUTHENTICATE_WITH_NFC
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_AUTHENTICATE_WITH_NFC
uint16_t uniffi_yntra_core_checksum_func_authenticate_with_nfc(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_AUTHENTICATE_WITH_SITHS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_AUTHENTICATE_WITH_SITHS
uint16_t uniffi_yntra_core_checksum_func_authenticate_with_siths(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_CLEAR_OBSERVERS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_CLEAR_OBSERVERS
uint16_t uniffi_yntra_core_checksum_func_clear_observers(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_COMPLETE_AUTH_SESSION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_COMPLETE_AUTH_SESSION
uint16_t uniffi_yntra_core_checksum_func_complete_auth_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_CREATE_JOB_TICKET
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_CREATE_JOB_TICKET
uint16_t uniffi_yntra_core_checksum_func_create_job_ticket(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_CREATE_WORKSPACE_VIA_HUB
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_CREATE_WORKSPACE_VIA_HUB
uint16_t uniffi_yntra_core_checksum_func_create_workspace_via_hub(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_EVENT
uint16_t uniffi_yntra_core_checksum_func_delete_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_NOTE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_NOTE
uint16_t uniffi_yntra_core_checksum_func_delete_note(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_TIME_REPORT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_TIME_REPORT
uint16_t uniffi_yntra_core_checksum_func_delete_time_report(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_WORKSPACE_VIA_HUB
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_DELETE_WORKSPACE_VIA_HUB
uint16_t uniffi_yntra_core_checksum_func_delete_workspace_via_hub(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_FAIL_AUTH_SESSION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_FAIL_AUTH_SESSION
uint16_t uniffi_yntra_core_checksum_func_fail_auth_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GENERATE_TOTP_SECRET
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GENERATE_TOTP_SECRET
uint16_t uniffi_yntra_core_checksum_func_generate_totp_secret(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_BANKID_AUTH_SESSION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_BANKID_AUTH_SESSION
uint16_t uniffi_yntra_core_checksum_func_get_bankid_auth_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_BLOCKS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_BLOCKS
uint16_t uniffi_yntra_core_checksum_func_get_blocks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_CLIENTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_CLIENTS
uint16_t uniffi_yntra_core_checksum_func_get_clients(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_EVENTS
uint16_t uniffi_yntra_core_checksum_func_get_events(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_JOB_TICKETS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_JOB_TICKETS
uint16_t uniffi_yntra_core_checksum_func_get_job_tickets(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_JOURNALS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_JOURNALS
uint16_t uniffi_yntra_core_checksum_func_get_journals(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_MEDICATIONS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_MEDICATIONS
uint16_t uniffi_yntra_core_checksum_func_get_medications(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_MESSAGES
uint16_t uniffi_yntra_core_checksum_func_get_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_NOTES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_NOTES
uint16_t uniffi_yntra_core_checksum_func_get_notes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_REPORTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_REPORTS
uint16_t uniffi_yntra_core_checksum_func_get_reports(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_TEAMS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_TEAMS
uint16_t uniffi_yntra_core_checksum_func_get_teams(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_TIME_REPORTS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_TIME_REPORTS
uint16_t uniffi_yntra_core_checksum_func_get_time_reports(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_TODOS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_TODOS
uint16_t uniffi_yntra_core_checksum_func_get_todos(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_USERS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_USERS
uint16_t uniffi_yntra_core_checksum_func_get_users(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_WORKSPACE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_WORKSPACE
uint16_t uniffi_yntra_core_checksum_func_get_workspace(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_WORKSPACES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_GET_WORKSPACES
uint16_t uniffi_yntra_core_checksum_func_get_workspaces(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_INITIATE_BANKID_AUTH
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_INITIATE_BANKID_AUTH
uint16_t uniffi_yntra_core_checksum_func_initiate_bankid_auth(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_INVITE_USER_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_INVITE_USER_VIA_DIRECTORY
uint16_t uniffi_yntra_core_checksum_func_invite_user_via_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_MARK_MESSAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_MARK_MESSAGE_READ
uint16_t uniffi_yntra_core_checksum_func_mark_message_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_REGISTER_OBSERVER
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_REGISTER_OBSERVER
uint16_t uniffi_yntra_core_checksum_func_register_observer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SEND_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SEND_MESSAGE
uint16_t uniffi_yntra_core_checksum_func_send_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SET_USER_PASSWORD
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SET_USER_PASSWORD
uint16_t uniffi_yntra_core_checksum_func_set_user_password(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SUBMIT_BANKID_PIN
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SUBMIT_BANKID_PIN
uint16_t uniffi_yntra_core_checksum_func_submit_bankid_pin(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SUBMIT_JOB_COMPLETION
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SUBMIT_JOB_COMPLETION
uint16_t uniffi_yntra_core_checksum_func_submit_job_completion(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SYNC_DATABASE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_SYNC_DATABASE
uint16_t uniffi_yntra_core_checksum_func_sync_database(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_TOGGLE_TODO
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_TOGGLE_TODO
uint16_t uniffi_yntra_core_checksum_func_toggle_todo(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_AUTH_SESSION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_AUTH_SESSION_STATUS
uint16_t uniffi_yntra_core_checksum_func_update_auth_session_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_CLIENT_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_CLIENT_PROFILE
uint16_t uniffi_yntra_core_checksum_func_update_client_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_EVENT
uint16_t uniffi_yntra_core_checksum_func_update_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_EVENT_TIME
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_EVENT_TIME
uint16_t uniffi_yntra_core_checksum_func_update_event_time(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_JOB_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_JOB_STATUS
uint16_t uniffi_yntra_core_checksum_func_update_job_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_NOTE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_NOTE
uint16_t uniffi_yntra_core_checksum_func_update_note(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_REPORT_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_REPORT_STATUS
uint16_t uniffi_yntra_core_checksum_func_update_report_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_TIME_REPORT_STATUS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_TIME_REPORT_STATUS
uint16_t uniffi_yntra_core_checksum_func_update_time_report_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_USER_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_USER_PROFILE
uint16_t uniffi_yntra_core_checksum_func_update_user_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_USER_ROLE
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_USER_ROLE
uint16_t uniffi_yntra_core_checksum_func_update_user_role(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_USER_VIA_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_USER_VIA_DIRECTORY
uint16_t uniffi_yntra_core_checksum_func_update_user_via_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_WORKSPACE_GENERAL
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_WORKSPACE_GENERAL
uint16_t uniffi_yntra_core_checksum_func_update_workspace_general(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_WORKSPACE_MODULES
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_WORKSPACE_MODULES
uint16_t uniffi_yntra_core_checksum_func_update_workspace_modules(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_WORKSPACE_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_UPDATE_WORKSPACE_SETTINGS
uint16_t uniffi_yntra_core_checksum_func_update_workspace_settings(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_VERIFY_EMAIL_PASSWORD
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_VERIFY_EMAIL_PASSWORD
uint16_t uniffi_yntra_core_checksum_func_verify_email_password(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_VERIFY_USER_TOTP
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_FUNC_VERIFY_USER_TOTP
uint16_t uniffi_yntra_core_checksum_func_verify_user_totp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_METHOD_DATABASEOBSERVER_ON_DATABASE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_YNTRA_CORE_CHECKSUM_METHOD_DATABASEOBSERVER_ON_DATABASE_CHANGED
uint16_t uniffi_yntra_core_checksum_method_databaseobserver_on_database_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_YNTRA_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_YNTRA_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_yntra_core_uniffi_contract_version(void
    
);
#endif

