[workspace]
members = [
    "yntra-core",
    "yntra-ui",
    "yntra-uniffi-bindgen"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
uniffi = { version = "0.28", features = ["tokio"] }
rkyv = { version = "0.8", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde", "js"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
dioxus = "0.7"
dioxus-logger = "0.7"
log = "0.4"
rusqlite = { version = "0.32", features = ["bundled"] }
tokio = { version = "1.40", features = ["time", "rt", "macros", "sync"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Worker", "console", "Navigator"] }
js-sys = "0.3"
fluent-bundle = "0.15"
unic-langid = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
totp-rs = { version = "5.7.0", default-features = false, features = ["gen_secret"] }
qrcodegen = "1.4.0"

# Workspace members
yntra-core = { path = "./yntra-core" }
