version: "3.8"

services:
  libsql-sync:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    container_name: yntra-libsql-sync-primary
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
    volumes:
      - ./target/local_sqld_data:/var/lib/sqld
    restart: unless-stopped
