// AUTO-GENERATED by scripts/generate_design_tokens.py - DO NOT EDIT DIRECTLY
import SwiftUI

public enum ColorTokens {
    public static let primary = Color(red: 0.145, green: 0.388, blue: 0.922)
    public static let primaryDark = Color(red: 0.114, green: 0.306, blue: 0.847)
    public static let backgroundDark = Color(red: 0.055, green: 0.067, blue: 0.090)
    public static let cardDark = Color(red: 0.067, green: 0.086, blue: 0.114)
    public static let popoverDark = Color(red: 0.067, green: 0.086, blue: 0.114)
    public static let foregroundDark = Color(red: 0.980, green: 0.980, blue: 0.980)
    public static let mutedDark = Color(red: 0.137, green: 0.165, blue: 0.208)
    public static let mutedForegroundDark = Color(red: 0.643, green: 0.690, blue: 0.753)
    public static let borderDark = Color(red: 0.137, green: 0.165, blue: 0.208)
    public static let inputDark = Color(red: 0.106, green: 0.129, blue: 0.165)
    public static let ring = Color(red: 0.231, green: 0.510, blue: 0.965)
    public static let success = Color(red: 0.063, green: 0.725, blue: 0.506)
    public static let warning = Color(red: 0.961, green: 0.620, blue: 0.043)
    public static let destructive = Color(red: 0.937, green: 0.267, blue: 0.267)
}
