// AUTO-GENERATED by scripts/generate_design_tokens.py - DO NOT EDIT DIRECTLY
package com.yntra.app.ui.theme

import androidx.compose.ui.graphics.Color

object ColorTokens {
    val Primary = Color(0xFF2563EB)
    val PrimaryDark = Color(0xFF1D4ED8)
    val BackgroundDark = Color(0xFF0E1117)
    val CardDark = Color(0xFF11161D)
    val PopoverDark = Color(0xFF11161D)
    val ForegroundDark = Color(0xFFFAFAFA)
    val MutedDark = Color(0xFF232A35)
    val MutedForegroundDark = Color(0xFFA4B0C0)
    val BorderDark = Color(0xFF232A35)
    val InputDark = Color(0xFF1B212A)
    val Ring = Color(0xFF3B82F6)
    val Success = Color(0xFF10B981)
    val Warning = Color(0xFFF59E0B)
    val Destructive = Color(0xFFEF4444)
}
