#!/usr/bin/env python3
"""
Yntra Platform Design Token Code Generator Pipeline
Reads tokens/design_tokens.json and generates target-native code tokens for:
- Android (Jetpack Compose ColorTokens.kt and res/values/colors.xml)
- iOS (SwiftUI ColorTokens.swift)
"""

import json
import os

def load_tokens(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_android_kt(tokens, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    colors = tokens['color']
    
    kt_code = """// AUTO-GENERATED by scripts/generate_design_tokens.py - DO NOT EDIT DIRECTLY
package com.yntra.app.ui.theme

import androidx.compose.ui.graphics.Color

object ColorTokens {
"""
    for key, data in colors.items():
        r, g, b = data['rgb']
        pascal_key = "".join(part.capitalize() for part in key.split('_'))
        kt_code += f"    val {pascal_key} = Color(0xFF{data['hex'].lstrip('#').upper()})\n"
    
    kt_code += "}\n"
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(kt_code)
    print(f"Generated Android Kotlin tokens -> {out_path}")

def generate_android_xml(tokens, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    colors = tokens['color']
    
    xml_code = """<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by scripts/generate_design_tokens.py - DO NOT EDIT DIRECTLY -->
<resources>
"""
    xml_mapping = {
        "primary": "colorPrimary",
        "primary_dark": "colorPrimaryDark",
        "ring": "colorAccent",
        "background_dark": "colorBackground",
        "card_dark": "colorSurface",
        "foreground_dark": "colorTextPrimary",
        "muted_foreground_dark": "colorTextSecondary"
    }
    
    for key, xml_name in xml_mapping.items():
        if key in colors:
            xml_code += f'    <color name="{xml_name}">{colors[key]["hex"]}</color>\n'
            
    xml_code += "</resources>\n"
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(xml_code)
    print(f"Generated Android XML colors -> {out_path}")

def generate_ios_swift(tokens, out_path):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    colors = tokens['color']
    
    swift_code = """// AUTO-GENERATED by scripts/generate_design_tokens.py - DO NOT EDIT DIRECTLY
import SwiftUI

public enum ColorTokens {
"""
    for key, data in colors.items():
        r, g, b = data['rgb']
        r_f, g_f, b_f = r / 255.0, g / 255.0, b / 255.0
        pascal_key = "".join(part.capitalize() for part in key.split('_'))
        swift_code += f"    public static let {pascal_key[:1].lower() + pascal_key[1:]} = Color(red: {r_f:.3f}, green: {g_f:.3f}, blue: {b_f:.3f})\n"
        
    swift_code += "}\n"
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(swift_code)
    print(f"Generated iOS SwiftUI tokens -> {out_path}")

def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    tokens_path = os.path.join(root, "tokens", "design_tokens.json")
    
    if not os.path.exists(tokens_path):
        print(f"Tokens file not found: {tokens_path}")
        return
        
    tokens = load_tokens(tokens_path)
    
    android_kt = os.path.join(root, "yntra-android", "app", "src", "main", "java", "com", "yntra", "app", "ui", "theme", "ColorTokens.kt")
    android_xml = os.path.join(root, "yntra-android", "app", "src", "main", "res", "values", "colors.xml")
    ios_swift = os.path.join(root, "yntra-ios", "YntraIOS", "Theme", "ColorTokens.swift")
    
    generate_android_kt(tokens, android_kt)
    generate_android_xml(tokens, android_xml)
    generate_ios_swift(tokens, ios_swift)
    print("Cross-platform design token sync complete.")

if __name__ == "__main__":
    main()
