use super::types::{
    BlockDefinition, BlockDomainCategory, BlockNavChild, BlockNavItem, EnterpriseStandardsSpec,
    ModuleTier,
};

pub static BLOCK_REGISTRY: &[BlockDefinition] = &[
    // --- CORE WORK OS ---
    BlockDefinition {
        id: "dashboard",
        name: "Dashboard",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["SOC2-Type-II", "ISO-27001"],
            supported_protocols: &["REST", "WebSockets"],
            enterprise_connectors: &["Yntra Unified Gateway"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "dashboard",
            label_key: "section-dashboard",
            path: "dashboard",
            icon: "dashboard",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "messaging",
        name: "Messaging",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["E2EE-Matrix", "HIPAA-Messaging"],
            supported_protocols: &["WebSockets", "WebRTC-DataChannel"],
            enterprise_connectors: &["Slack Enterprise Grid", "Microsoft Teams"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "messaging",
            label_key: "section-messaging",
            path: "messaging",
            icon: "messaging",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: Some("unread_messages"),
        }],
    },
    BlockDefinition {
        id: "scheduling",
        name: "Scheduling",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["CalDAV-RFC4791", "iCalendar-RFC5545"],
            supported_protocols: &["REST", "CalDAV"],
            enterprise_connectors: &["Google Workspace", "Microsoft Exchange / 365"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "time_group",
            label_key: "sidebar-time-management",
            path: "scheduling",
            icon: "clock",
            allowed_roles: Some(&["platform_admin", "admin", "user", "assistant"]),
            section: "main",
            badge_key: None,
            children: Some(&[
                BlockNavChild {
                    id: "scheduling",
                    label_key: "section-scheduling",
                    path: "scheduling",
                    icon: "scheduling",
                    required_block_id: None,
                },
                BlockNavChild {
                    id: "time",
                    label_key: "section-time",
                    path: "time",
                    icon: "time",
                    required_block_id: Some("time"),
                },
            ]),
        }],
    },
    BlockDefinition {
        id: "directory",
        name: "Directory",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["SCIM-2.0", "SAML-2.0", "OpenID-Connect"],
            supported_protocols: &["LDAP", "REST/JSON"],
            enterprise_connectors: &["Okta", "Azure AD / Entra ID", "Ping Identity"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "directory",
            label_key: "section-directory",
            path: "directory",
            icon: "directory",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "admin_panel",
        name: "Admin Panel",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["SOC2-Audit-Logging", "NIST-800-53", "RBAC"],
            supported_protocols: &["REST", "gRPC"],
            enterprise_connectors: &["Splunk Enterprise", "Datadog", "AWS CloudTrail"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "admin_panel",
            label_key: "section-admin-panel",
            path: "admin_panel",
            icon: "shield-check",
            allowed_roles: Some(&["platform_admin", "admin"]),
            section: "main",
            children: Some(&[
                BlockNavChild {
                    id: "admin_onboarding",
                    label_key: "admin-tab-onboarding",
                    path: "admin_panel",
                    icon: "sparkles",
                    required_block_id: None,
                },
                BlockNavChild {
                    id: "admin_invitations",
                    label_key: "admin-tab-invitations",
                    path: "admin_panel",
                    icon: "user-plus",
                    required_block_id: None,
                },
                BlockNavChild {
                    id: "admin_rbac",
                    label_key: "admin-tab-rbac",
                    path: "admin_panel",
                    icon: "shield-alert",
                    required_block_id: None,
                },
                BlockNavChild {
                    id: "admin_audit",
                    label_key: "admin-tab-audit",
                    path: "admin_panel",
                    icon: "file-text",
                    required_block_id: None,
                },
            ]),
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "agentic_ai",
        name: "Agentic AI & Voice",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["EU-AI-Act", "NIST-AI-RMF"],
            supported_protocols: &["gRPC", "WebSockets-VoiceStream"],
            enterprise_connectors: &["Anthropic Claude API", "OpenAI Enterprise"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "agentic_ai",
            label_key: "section-agentic-ai",
            path: "agentic_ai",
            icon: "sparkles",
            allowed_roles: Some(&["platform_admin", "admin", "user"]),
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "ecosystem_integrations",
        name: "Ecosystem Integrations",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["OpenAPI-v3.1", "OAuth2.0-RFC6749"],
            supported_protocols: &["REST", "Webhooks"],
            enterprise_connectors: &["Zapier Enterprise", "Make.com", "MuleSoft"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "ecosystem_integrations",
            label_key: "section-integrations",
            path: "integrations",
            icon: "plug",
            allowed_roles: Some(&["platform_admin", "admin", "user"]),
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "support_center",
        name: "Support Center",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["ITIL-v4", "SLA-Tracking"],
            supported_protocols: &["REST", "Email-IMAP"],
            enterprise_connectors: &["Zendesk", "ServiceNow", "Jira Service Management"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "support_center",
            label_key: "section-support-center",
            path: "support_center",
            icon: "life-buoy",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },

    // --- ENTERPRISE HEALTHCARE (HL7 / FHIR / DICOM / EHR) ---
    BlockDefinition {
        id: "health_clinic",
        name: "Health Clinic EMR",
        domain_categories: &[BlockDomainCategory::EnterpriseHealthcare],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["HL7-FHIR-R4", "DICOM-Web", "HIPAA-Security-Rule", "21-CFR-Part-11"],
            supported_protocols: &["REST/FHIR-JSON", "DICOM-STOW-RS", "HL7-v2-MLLP"],
            enterprise_connectors: &["Epic Systems EMR", "Cerner Millennium", "Allscripts TouchWorks"],
            jurisdiction: "US-HIPAA / EU-MDR",
        },
        navigation: &[BlockNavItem {
            id: "health_clinic",
            label_key: "settings-blocks-health-clinic-name",
            path: "health_clinic",
            icon: "heart",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "journals",
        name: "Care Journals",
        domain_categories: &[BlockDomainCategory::EnterpriseHealthcare, BlockDomainCategory::EnterpriseAcademics],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["HIPAA-Privacy-Rule", "Patient-Access-API", "GDPR-HealthData"],
            supported_protocols: &["REST/FHIR-ClinicalNote", "Audit-Log-RFC5424"],
            enterprise_connectors: &["Epic CareEverywhere", "Cerner CareAware"],
            jurisdiction: "US-HIPAA / EU-GDPR",
        },
        navigation: &[BlockNavItem {
            id: "journals",
            label_key: "assistance-daily-notes",
            path: "journals",
            icon: "book-open",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "medications",
        name: "Medications & e-Prescribing",
        domain_categories: &[BlockDomainCategory::EnterpriseHealthcare],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["HL7-FHIR-MedicationStatement", "NCPDP-SCRIPT-v2017071", "FDA-BarCode-Labeling"],
            supported_protocols: &["REST/FHIR-JSON", "NCPDP-EDI"],
            enterprise_connectors: &["Surescripts Network", "Epic Willow Pharmacy"],
            jurisdiction: "US-FDA / EU-EMA",
        },
        navigation: &[BlockNavItem {
            id: "medications",
            label_key: "assistance-active-medication-list",
            path: "medications",
            icon: "activity",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "client_portal",
        name: "Client & Patient Portal",
        domain_categories: &[BlockDomainCategory::EnterpriseHealthcare],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["SMART-on-FHIR", "HIPAA-Right-of-Access", "WCAG-2.1-AA"],
            supported_protocols: &["OAuth2-SMART", "REST/FHIR"],
            enterprise_connectors: &["MyChart Portal Sync", "HealtheLife Patient Portal"],
            jurisdiction: "US-HIPAA / EU-GDPR",
        },
        navigation: &[BlockNavItem {
            id: "client_portal",
            label_key: "section-assistance",
            path: "client_portal",
            icon: "heart",
            allowed_roles: Some(&["client"]),
            section: "main",
            children: None,
            badge_key: None,
        }],
    },

    // --- ENTERPRISE ACADEMICS (LTI / CANVAS / FERPA) ---
    BlockDefinition {
        id: "academics",
        name: "Academics & Course Hub",
        domain_categories: &[BlockDomainCategory::EnterpriseAcademics],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["IMS-LTI-1.3-Advantage", "OneRoster-v1.2", "FERPA-Compliant"],
            supported_protocols: &["OAuth2-LTI", "REST/JSON"],
            enterprise_connectors: &["Canvas LMS API", "Blackboard Learn REST", "Moodle LTI"],
            jurisdiction: "US-FERPA / Global",
        },
        navigation: &[BlockNavItem {
            id: "academics",
            label_key: "settings-blocks-academics-name",
            path: "academics",
            icon: "book-open",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "attendance",
        name: "Student Attendance Tracking",
        domain_categories: &[BlockDomainCategory::EnterpriseAcademics],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["OneRoster-Attendance-v1.2", "FERPA-Audit-Logging"],
            supported_protocols: &["REST/JSON", "NFC-Badge-Read"],
            enterprise_connectors: &["PowerSchool SIS", "Infinite Campus SIS"],
            jurisdiction: "US-FERPA / Global",
        },
        navigation: &[BlockNavItem {
            id: "attendance",
            label_key: "settings-blocks-attendance-name",
            path: "attendance",
            icon: "user-check",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "library",
        name: "Library & Learning Catalog",
        domain_categories: &[BlockDomainCategory::EnterpriseAcademics],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["NCIP-v2.0", "Z39.50", "MARC21-Format"],
            supported_protocols: &["SIP2", "NCIP-XML", "REST/JSON"],
            enterprise_connectors: &["Ex Libris Alma", "OCLC WorldShare", "Follett Destiny"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "library",
            label_key: "settings-blocks-library-name",
            path: "library",
            icon: "book-open",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "report_cards",
        name: "Report Cards & Transcripts",
        domain_categories: &[BlockDomainCategory::EnterpriseAcademics],
        tier: ModuleTier::EnterpriseVertical,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["PESC-XML-AcademicTranscript", "FERPA-Privacy"],
            supported_protocols: &["REST/JSON", "PDF/A-DigitalSignature"],
            enterprise_connectors: &["Parchment Exchange", "PowerSchool SIS"],
            jurisdiction: "US-FERPA / Global",
        },
        navigation: &[BlockNavItem {
            id: "report_cards",
            label_key: "settings-blocks-report-cards-name",
            path: "report_cards",
            icon: "file-check",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },

    // --- FIELD OPERATIONS & LOGISTICS ---
    BlockDefinition {
        id: "jobs",
        name: "Jobs & Work Orders",
        domain_categories: &[BlockDomainCategory::FieldAndLogistics],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["ISO-9001-QualityManagement", "OSHA-WorkSafety"],
            supported_protocols: &["REST", "WebSockets"],
            enterprise_connectors: &["Salesforce Field Service", "ServiceTitan"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "jobs",
            label_key: "jobs-nav",
            path: "jobs",
            icon: "jobs",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "dispatch",
        name: "Dispatch & Shift Planner",
        domain_categories: &[BlockDomainCategory::FieldAndLogistics],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["GTFS-Flex", "EU-WorkingTimeDirective-2003/88"],
            supported_protocols: &["REST", "WebSockets"],
            enterprise_connectors: &["Workday Workforce", "SAP SuccessFactors"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "dispatch",
            label_key: "section-dispatch",
            path: "dispatch",
            icon: "calendar",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "live_map",
        name: "Live Map Telematics",
        domain_categories: &[BlockDomainCategory::FieldAndLogistics],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["GTFS-Realtime", "ISO-19115-GeographicInformation"],
            supported_protocols: &["MQTT", "WebSockets", "GeoJSON"],
            enterprise_connectors: &["Samsara Telematics", "Geotab API"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "live_map",
            label_key: "section-live-map",
            path: "live_map",
            icon: "map-pin",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "fleet",
        name: "Fleet & Asset Management",
        domain_categories: &[BlockDomainCategory::FieldAndLogistics],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["SAE-J1939-OBDII", "ISO-28000-SupplyChainSecurity"],
            supported_protocols: &["CAN-Bus", "REST/JSON"],
            enterprise_connectors: &["Verizon Connect", "Fleetio API"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "fleet",
            label_key: "section-fleet",
            path: "fleet",
            icon: "truck",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "booking_widget",
        name: "Customer Booking Widget",
        domain_categories: &[BlockDomainCategory::FieldAndLogistics],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["PCI-DSS-v4.0", "WCAG-2.1-AA"],
            supported_protocols: &["HTTPS-Embed", "REST"],
            enterprise_connectors: &["Stripe Connect", "Adyen Webhooks"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "booking_widget",
            label_key: "section-booking-widget",
            path: "booking_widget",
            icon: "code",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
    BlockDefinition {
        id: "finance",
        name: "Finance & Invoicing",
        domain_categories: &[BlockDomainCategory::CoreWorkOS],
        tier: ModuleTier::CorePlatform,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["Peppol-BIS-Billing-3.0", "EU-e-Invoicing-EN16931"],
            supported_protocols: &["REST/JSON", "UBL-2.1-XML"],
            enterprise_connectors: &["Fortnox API", "Visma eEkonomi", "QuickBooks Online"],
            jurisdiction: "Global",
        },
        navigation: &[BlockNavItem {
            id: "finance",
            label_key: "settings-blocks-finance-name",
            path: "finance",
            icon: "credit-card",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },

    // --- REGIONAL REGULATORY & TAX EXTENSIONS ---
    BlockDefinition {
        id: "rut_exports",
        name: "RUT/ROT Tax Deductions",
        domain_categories: &[BlockDomainCategory::RegionalRegulatory],
        tier: ModuleTier::RegionalExtension,
        standards: EnterpriseStandardsSpec {
            compliance_standards: &["Skatteverket-RUT-ROT-XML-v2.1", "SE-TaxCode-Chapter67"],
            supported_protocols: &["REST", "Skatteverket-XML-SOAP"],
            enterprise_connectors: &["Skatteverket Direct Gateway", "Fortnox RUT Integration"],
            jurisdiction: "SE-SKAT",
        },
        navigation: &[BlockNavItem {
            id: "rut_exports",
            label_key: "section-rut-exports",
            path: "rut_exports",
            icon: "file-text",
            allowed_roles: None,
            section: "main",
            children: None,
            badge_key: None,
        }],
    },
];

